# Generated by Django 2.2 on 2019-05-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190515_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='votes_total',
            field=models.IntegerField(default=1),
        ),
    ]
