# Generated by Django 2.2 on 2019-05-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_votes_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='votes_total',
        ),
    ]
