# Generated by Django 2.2 on 2019-05-15 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190515_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 19, 29, 14, 670518)),
        ),
    ]
